package com.yc.verbaltalk.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yc.verbaltalk.chat.bean.LoveHealDetDetailsBean;

import com.yc.verbaltalk.model.dao.LoveHealDetDetailsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loveHealDetDetailsBeanDaoConfig;

    private final LoveHealDetDetailsBeanDao loveHealDetDetailsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loveHealDetDetailsBeanDaoConfig = daoConfigMap.get(LoveHealDetDetailsBeanDao.class).clone();
        loveHealDetDetailsBeanDaoConfig.initIdentityScope(type);

        loveHealDetDetailsBeanDao = new LoveHealDetDetailsBeanDao(loveHealDetDetailsBeanDaoConfig, this);

        registerDao(LoveHealDetDetailsBean.class, loveHealDetDetailsBeanDao);
    }
    
    public void clear() {
        loveHealDetDetailsBeanDaoConfig.clearIdentityScope();
    }

    public LoveHealDetDetailsBeanDao getLoveHealDetDetailsBeanDao() {
        return loveHealDetDetailsBeanDao;
    }

}
